### ISSUE TITLE
New JavaScript course on Codecademy?

### ISSUE THREAD

**Issue by ChielHackman** [ummahusla/Codecademy-Exercise-Answers#101]
> Hi there, this version of the JavaScript course is being taken down in Summer 2017; we recommend you try our new Learn JavaScript course. Please read our blog post for more information.

**Comment by ummahusla** [comment]
@ChielHackman So what's the purpose of this issue then?

**Comment by ChielHackman** [comment]
Sorry, was getting confused with the fact they have 2 courses:
JavaScript
Learn JavaScript

Actual question:
Do you want to add the Learn JavaScript?
If so, please let me know in which section it belongs and I will make a pull request.

**Comment by ChielHackman** [comment]
[Here is the blog about their changes](https://www.codecademy.com/blog/important-changes-to-codecademy-courses?utm_campaign=composer_course_replacement&utm_medium=int_butterbar_course_page&utm_source=codecademy_platform)

**Comment by ummahusla** [comment]
@ChielHackman Right I see what you mean. I guess `Learn JavaScript` can be placed in [**Web Developer Skills**](https://github.com/ummahusla/Codecademy-Exercise-Answers/tree/master/Web%20Developer%20Skills) folder as there are lots of the similar `Learn X` folders.

**Comment by ummahusla** [comment]
Additionally, we will need to add a link to [Web Developer Skills section ](https://github.com/ummahusla/Codecademy-Exercise-Answers#web-application-skills) in repo's `readme.md`.

**Comment by ChielHackman** [comment]
@ummahusla Thanks for the quick response! Will close this issue and you'll see the pull request coming by soon.

**Comment by ummahusla** [comment]
@ChielHackman Thanks mate! I appreciate your effort 👍
