### ISSUE TITLE
Forgot to log to console

### ISSUE THREAD

**Issue by alexp9982** [ummahusla/Codecademy-Exercise-Answers#119]
In Introduction to JavaScript; Variables; 4. Undefined, you forgot to log the first variable you defined, as CodeCademy said to do. It still will allow you to move on to the next one though, but the code should be fixed. I'll give you the correct code.

let notDefined;
console.log(notDefined);
let valueless;
console.log(valueless);

**Comment by ummahusla** [comment]
@alexp9982 Good job spotting this. Can you please make a PR for this? 👍

**Comment by alexp9982** [comment]
Sorry, I’m kinda new to github and I don’t know what a PR is, sorry.

**Comment by ummahusla** [comment]
@alexp9982 This is a very good place to start. Here are a couple of good resources to start with:

* https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
* https://help.github.com/articles/creating-a-pull-request/

**Comment by alexp9982** [comment]
Extremely busy recently, will do pretty soon, along with a bunch of changes/corrections to Javascript

**Comment by ummahusla** [comment]
@alexp9982 Great 👍

**Comment by alexp9982** [comment]
For some reason, there's a problem with the unit 12 in python in lesson 02
The devil in the details

I can't copy the file, probably because there's a colon in the name of the
file, I highly recommend fixing this
Rename the 6-PSA: Buffering Data.py and remove the colon so I can clone the
repository.

**Comment by alexp9982** [comment]
I need you to accept my pull request.

**Comment by ummahusla** [comment]
@alexp9982 Done, thank you very much 💯
