### ISSUE TITLE
Create contributing guide

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/Codecademy-Exercise-Answers#18]
Guide should clearly explain how to add new exercises and answers to the repository without breaking a "global formatting style", so all answers should be formatted in one way.

**Comment by jgaidimas** [comment]
I believe the best formatting style is to create folders for each lesson. Inside each folder should be a readme file that is numbered with answers. For example:
JavaScript/Introduction to Programming/readme.md
This allows all the answers for each lesson to be viewed at once, so there is less time wasted searching for answers. If we are in agreement, I would be happy to create a formatting guide for this style.

**Comment by ummahusla** [comment]
@jgaidimas Well, this is how it how I was structuring this repo, and I believe this is most appropriate way of keeping it simple as well as easy to access the answers. It would be great of you could create a formating-guide.md and put it into the root folder.

**Comment by jgaidimas** [comment]
Alright, should I restructure parts of the repo that don't follow this format as well?

**Comment by ummahusla** [comment]
@jgaidimas If you have time for that you can give it a go. Then the whole repository will be well-structured and newcomers will be able to access the data as well as to commit a new changes.

**Comment by jgaidimas** [comment]
@ummahusla Should folders be numbered like this: http://prntscr.com/9lpr2a? I think it makes the most sense to do numbered, as it's easiest to navigate. I'm also thinking the contribute readme.md from complete skills/languages folders should be removed.

**Comment by ummahusla** [comment]
@jgaidimas I was thinking about numering the folders, it's a good idea. About completed paths, it's a good idea as well.

**Comment by Moulick** [comment]
Another big problem is that there are errors while cloning this repo on windows gives a lot of errors due to use of ? and other prohibited characters

**Comment by ummahusla** [comment]
@Moulick Can you please create a new issue and describe everything in details. Thanks

**Comment by ummahusla** [comment]
Closed
