### ISSUE TITLE
Please submit your suggestions

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/Codecademy-Exercise-Answers#26]
To help us improve the Codecademy exercise answers repository, please submit your thoughts, ideas and suggestions, by creating a new issue with a tag "help wanted" or "suggestion". 

Thanks

**Comment by bluntedmice** [comment]
I don't think posting the answers will help anyone learning

**Comment by ummahusla** [comment]
@bluntedmice Why do you think that? It would be very nice if you could be more precise.

**Comment by bluntedmice** [comment]
spelling error**

**Comment by bluntedmice** [comment]
This repo comes up whenever I google help on a answer and personally it would of been cool if I had to figure it out but not get the full answer handed

**Comment by bluntedmice** [comment]
This is basically huge cheatsheet , i hope people don't look at these religiously

**Comment by ummahusla** [comment]
@bluntedmice If you want to get an explanation or discuss the exercise please check [**Codecademy Discuss**](https://discuss.codecademy.com/). This repository is only created for educational purposes to help people who want to learn to code and who might be stuck on a task and need a someone's help.

**Comment by ummahusla** [comment]
Closed
