### ISSUE TITLE
Text of exercises and structure

### ISSUE THREAD

**Issue by paulcarroty** [ummahusla/Codecademy-Exercise-Answers#38]
Many of source code it's not readable without the text of exercise, and theory it's necessary. Any ideas for improve it?

I'm now trying to create a good [readable structure](https://github.com/paulcarroty/Ruby-Snippets/tree/master/Codecademy%20Ruby) and has think to merge some source code from [here](https://github.com/ummahusla/Codecademy-Exercise-Answers/tree/master/Language%20Skills/Ruby), but your structure have horrible looks.

**Comment by ummahusla** [comment]
Text of exercises are often a subject to change, so I wouldn't stress too much about it. Obviously in some of the language skills folder structure is far from being perfect. I will try to find some time to make a better structuring for many folders.

**Comment by paulcarroty** [comment]
@ummahusla 
> so I wouldn't stress too much about it
What about parser/downloader/etc? It may solve this problem. CC doesn't have an API, it's bad.

**Comment by ummahusla** [comment]
Thank you one more time. I will keep in mind your suggestions next time I will start working on repository structure.
