### ISSUE TITLE
The Big if  Conditionals & Control Flow problem slove

### ISSUE THREAD

**Issue by faizanalvi** [ummahusla/Codecademy-Exercise-Answers#56]
# Make sure that the_flying_circus() returns True
def the_flying_circus():
    if 3<4 or 15>=64:
        return True
        
    elif 4 == 4 and 5>=9:
        return False
    else:
            return True
![screenshot 1](https://cloud.githubusercontent.com/assets/18098390/16589919/c501b434-42ee-11e6-96b7-51767bd4466d.png)

**Comment by ummahusla** [comment]
Nice spot! Can you add a new pull request with updated code for this exercise? 

It would be nice, if you could tell which `Unit` are you looking in.
