### ISSUE TITLE
Remove ?, * and \ symbols from the folder names

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/Codecademy-Exercise-Answers#65]
Yesterday I had an issue with the repository on my Windows machine, because Windows doesn't allow `?`, `*` and `\` in the folder names.

**Comment by ummahusla** [comment]
Partly removed

**Comment by ummahusla** [comment]
I partly renamed all folders. Few moment ago tested now again on Windows and the issue is still exists.

**Comment by Moulick** [comment]
I was thinking of doing this for the Python under the Language Skills. It'll be a long task

**Comment by ummahusla** [comment]
@moulick Well at the moment it's top priority task from my point of view. I want to fix it to allow Windows users to interact with repository. So if you have time, ease take a look at it
 Thanks

**Comment by Moulick** [comment]
@ummahusla Should I also add file numbers like 1. Welcome!.py ?

**Comment by ummahusla** [comment]
@Moulick I would suggest to make it something like `01 Welcome.py` without dots or exclamation marks

**Comment by Moulick** [comment]
! @ # $ % ^ & ( ) _ - + = { } ] [ ' ; and dots are fine in windows...

**Comment by Moulick** [comment]
The following reserved characters:
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)



these are the problematic characters

**Comment by ummahusla** [comment]
I see, thanks for that. Even tho I would suggest not to use special characters.

**Comment by ummahusla** [comment]
Closed
