### ISSUE TITLE
In Language Skills/HTML & CSS, in HTML Basics II, Lesson 7, the font size code is incorrect

### ISSUE THREAD

**Issue by o355** [ummahusla/Codecademy-Exercise-Answers#77]
The instructions call for 10px, 20px, and 40px instead of what's there right now.

**Comment by ummahusla** [comment]
@o355 Hey! Thank you for pointing it out. Do you want to make a Pull Request with new changes or you want me to do that?

**Comment by o355** [comment]
I'll make a pull request very soon, I know there were a few other issues as well.

**Comment by ummahusla** [comment]
@o355 That's absolutely great. Thank you.

**Comment by o355** [comment]
@ummahusla Created the pull request

**Comment by ummahusla** [comment]
@o355 Thank you 👍
