### ISSUE TITLE
(Talker.js)  The code is wrong?

### ISSUE THREAD

**Issue by IgorFachini** [ummahusla/Codecademy-Exercise-Answers#89]
PATH = Web Developer Skills/Learn ReactJS Part I/Unit 03 Components Interacting/02 this props/10 handleEvent onEvent and this props on Event/Talker.js .

Talker.js  = This code is not accepting. 

Follow the correct code:

```
var React = require('react');
var ReactDOM = require('react-dom');
var Button = require('./Button');

var Talker = React.createClass({
  handleClick: function () {
    for (var speech = '', i = 0; i < 10000; i++) {
      speech += 'blah ';
    }
    alert(speech);
  },
  
  render: function () {
    return <Button onClick={this.handleClick} />;
  }
});

ReactDOM.render(
  <Talker />,
  document.getElementById('app')
);

```

**Comment by ummahusla** [comment]
@IgorFachini Hey! Can you create a PR for that?

**Comment by ummahusla** [comment]
@IgorFachini Hey, any updates?

**Comment by IgorFachini** [comment]
I'm sorry, I completely forgot to create a PR for this. I just created PR.

**Comment by ummahusla** [comment]
@IgorFachini Great thanks, will review it soon. 

#96
