### ISSUE TITLE
Modifying an element of a list in a function in Codecademy

### ISSUE THREAD

**Issue by muknerd** [ummahusla/Codecademy-Exercise-Answers#95]
Instructions
Change list_function so that: 
1. 1. Add 3 to the item at index one of the list.
2. Store the result back into index one.
3. Return the list
****************************************
def list_function(n):
    ns = []
    append.ns[0]=3
    return ns

**Comment by ummahusla** [comment]
@muknerd I'm slightly confused about that issue. Can you please explain what you are trying to achieve and what's the problem?

**Comment by ummahusla** [comment]
Closed
